### ISSUE TITLE
Home directory is polluted with .beamup directory

### ISSUE THREAD

**Issue by lpil** [tsloughter/beamup#55]
I think it would be best to have this be within an appropriate directory such as `~/.local`, `~/Library`, etc, similar to how the data and configuration directories work

**Comment by tsloughter** [comment]
Are you on macos? On Linux it shouldn't be `~/.beamup` for sure. What I did was utilize the results of https://docs.rs/dirs/5.0.1/dirs/ and in the cases of `None` I based it on what I believe to be common practice on macos/windows from similar tools.

I don't like it, and don't have macos to verify against. Even on Linux tools like rustup/cargo/npm use `~/.*`. Can beamup do better? Yes, I considered it playing it cautious to do this in the case `executable_dir` is `None`.

**Comment by lpil** [comment]
This was on Fedora Linux.

**Comment by tsloughter** [comment]
Weird... I'm on Fedora. Well crap, there must be a bug.

**Comment by lpil** [comment]
I just tested on fedora, alpine, and debian and this didn't happen! I must have make a mistake. Sorry about that
